# -*- coding: utf-8 -*-
"""simulate_iot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18arf_3TTryyjxBUuStXcSe1utmI5Yo-f
"""

import os
import json
import pandas as pd
import numpy as np
from datetime import datetime

# KONFIGURASI PATH
BASE_DIR     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATASET_PATH = os.path.join(BASE_DIR, "datasets", "pondsdata.csv")

# Mapping kolom Pondsdata → kolom standar yang dipakai model
# Sesuaikan key jika nama kolom di CSV berbeda
COLUMN_MAPPING = {
    "PH"         : "ph",
    "TEMP": "temperature",
    "TURBIDITY"  : "turbidity",
    "Pond"       : "station_id",    # kolom identifikasi stasiun/kolam
}

# Metadata stasiun (nama & deskripsi tiap kolam)
STATION_METADATA = {
    "pond_1": {
        "name"       : "Pond Station 1",
        "description": "Kolam ikan murrel — Guntur, Andhra Pradesh",
        "fish_stock" : "Murrel"
    },
    "pond_2": {
        "name"       : "Pond Station 2",
        "description": "Kolam ikan catla — Guntur, Andhra Pradesh",
        "fish_stock" : "Catla"
    },
    "pond_3": {
        "name"       : "Pond Station 3",
        "description": "Kolam multispecies — Guntur, Andhra Pradesh",
        "fish_stock" : "Multispecies"
    },
}

FEATURES = ["ph", "temperature", "turbidity"]

# LOAD & PERSIAPAN PONDSDATA

def load_pondsdata(path: str) -> pd.DataFrame:
    """Load dan normalkan Pondsdata."""
    df = pd.read_csv(path)

    # Rename kolom sesuai mapping (hanya kolom yang ada)
    rename_map = {k: v for k, v in COLUMN_MAPPING.items() if k in df.columns}
    df = df.rename(columns=rename_map)

    # Pastikan kolom features ada
    missing = [f for f in FEATURES if f not in df.columns]
    if missing:
        raise ValueError(
            f"Kolom berikut tidak ditemukan di Pondsdata: {missing}\n"
            f"Kolom tersedia: {list(df.columns)}\n"
            f"Sesuaikan COLUMN_MAPPING di simulate_iot.py"
        )

    # Drop baris dengan nilai kosong pada fitur utama
    df = df.dropna(subset=FEATURES)
    return df


def assign_station_ids(df: pd.DataFrame) -> pd.DataFrame:

    if "station_id" in df.columns:
        # Normalisasi nilai station_id ke format pond_1, pond_2, pond_3
        unique_stations = sorted(df["station_id"].unique())
        station_map = {s: f"pond_{i+1}" for i, s in enumerate(unique_stations[:3])}
        df["station_id"] = df["station_id"].map(station_map).fillna("pond_1")
    else:
        # Bagi data merata ke 3 stasiun berdasarkan index
        n = len(df)
        df = df.copy()
        df["station_id"] = pd.cut(
            np.arange(n),
            bins=3,
            labels=["pond_1", "pond_2", "pond_3"]
        ).astype(str)

    return df

# FUNGSI UTAMA: AMBIL KONDISI AIR PER STASIUN

def get_all_stations(df: pd.DataFrame) -> list:
    """
    Kembalikan list semua stasiun beserta kondisi air terkini (latest reading).
    Digunakan FE untuk menampilkan daftar titik kolam yang bisa dipilih.
    """
    stations = []
    for station_id, meta in STATION_METADATA.items():
        condition = get_latest_reading(df, station_id)
        stations.append({
            "station_id" : station_id,
            "name"       : meta["name"],
            "description": meta["description"],
            "fish_stock" : meta["fish_stock"],
            "water_condition": condition
        })
    return stations


def get_station_by_id(df: pd.DataFrame, station_id: str) -> dict:
    """
    Ambil kondisi air dari 1 stasiun spesifik berdasarkan station_id.
    Ini yang dipanggil ketika user memilih titik kolam di FE.

    Args:
        df         : DataFrame Pondsdata yang sudah di-load
        station_id : "pond_1" | "pond_2" | "pond_3"

    Returns:
        dict kondisi air stasiun tersebut
    """
    if station_id not in STATION_METADATA:
        raise ValueError(
            f"station_id '{station_id}' tidak valid. "
            f"Pilihan: {list(STATION_METADATA.keys())}"
        )

    meta      = STATION_METADATA[station_id]
    condition = get_latest_reading(df, station_id)

    return {
        "station_id"     : station_id,
        "name"           : meta["name"],
        "description"    : meta["description"],
        "fish_stock"     : meta["fish_stock"],
        "water_condition": condition,
        "fetched_at"     : datetime.now().isoformat()
    }


def get_latest_reading(df: pd.DataFrame, station_id: str) -> dict:
    """
    Ambil 1 pembacaan terbaru (baris terakhir) dari stasiun tertentu.
    Di sistem IoT nyata, ini akan diganti dengan real-time API call.
    """
    station_df = df[df["station_id"] == station_id]

    if station_df.empty:
        raise ValueError(f"Tidak ada data untuk stasiun '{station_id}'")

    # Ambil baris terakhir sebagai simulasi "data terkini dari sensor"
    latest = station_df.iloc[-1]

    return {
        "ph"         : round(float(latest["ph"]), 2),
        "temperature": round(float(latest["temperature"]), 2),
        "turbidity"  : round(float(latest["turbidity"]), 2),
    }


def get_station_statistics(df: pd.DataFrame, station_id: str) -> dict:
    """
    Statistik kondisi air per stasiun (min, max, mean, std).
    Opsional — bisa dikirim ke FE sebagai konteks historis.
    """
    station_df = df[df["station_id"] == station_id][FEATURES]

    if station_df.empty:
        return {}

    stats = station_df.agg(["mean", "min", "max", "std"]).round(2)
    return {
        feat: {
            "mean": stats.loc["mean", feat],
            "min" : stats.loc["min",  feat],
            "max" : stats.loc["max",  feat],
            "std" : stats.loc["std",  feat],
        }
        for feat in FEATURES
    }

# INISIALISASI (dipanggil sekali saat startup)

def init_iot_simulator(path: str = DATASET_PATH) -> pd.DataFrame:
    """
    Load dan siapkan Pondsdata. Panggil fungsi ini 1x di awal notebook/app.
    Kembalikan DataFrame yang siap dipakai oleh fungsi-fungsi lain.
    """
    df = load_pondsdata(path)
    df = assign_station_ids(df)
    print(f"[OK] IoT Simulator ready - {len(df)} records dari {df['station_id'].nunique()} stasiun")
    print(f"  Distribusi per stasiun:\n{df['station_id'].value_counts().to_string()}\n")
    return df


# DEMO (jalankan langsung untuk test)

if __name__ == "__main__":
    print("=" * 50)
    print("  AQUACULTURE ML - IoT SIMULATOR")
    print("=" * 50 + "\n")

    pond_df = init_iot_simulator()

    # Test ambil semua stasiun
    print("--- Semua Stasiun ---")
    all_stations = get_all_stations(pond_df)
    print(json.dumps(all_stations, indent=2))

    # Test ambil 1 stasiun
    print("\n--- Stasiun pond_1 ---")
    station = get_station_by_id(pond_df, "pond_1")
    print(json.dumps(station, indent=2))

    # Test statistik
    print("\n--- Statistik pond_2 ---")
    stats = get_station_statistics(pond_df, "pond_2")
    print(json.dumps(stats, indent=2))