# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJvHtvh7mKFp27zXqB0UyvmQ31wVjlZl
"""

import os
import json
import joblib
import numpy as np
import pandas as pd
from datetime import datetime

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score
)
from imblearn.over_sampling import SMOTE

# ─────────────────────────────────────────────
# KONFIGURASI PATH
# ─────────────────────────────────────────────
BASE_DIR      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATASET_PATH  = os.path.join(BASE_DIR, "datasets", "realfishdataset.csv")
MODEL_DIR     = os.path.join(BASE_DIR, "models")
MODEL_PATH    = os.path.join(MODEL_DIR, "fish_model.pkl")
ENCODER_PATH  = os.path.join(MODEL_DIR, "label_encoder.pkl")
METADATA_PATH = os.path.join(MODEL_DIR, "model_metadata.json")

FEATURES = ["ph", "temperature", "turbidity"]
TARGET   = "fish"

RANDOM_STATE = 42
TEST_SIZE    = 0.2

# ─────────────────────────────────────────────
# 1. LOAD & VALIDASI DATASET
# ─────────────────────────────────────────────
def load_dataset(path: str) -> pd.DataFrame:
    print(f"[1/6] Loading dataset dari: {path}")
    df = pd.read_csv(path)

    # Validasi kolom
    required_cols = FEATURES + [TARGET]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Kolom tidak ditemukan di dataset: {missing}")

    print(f"      [OK] Dataset loaded: {df.shape[0]} baris, {df.shape[1]} kolom")
    print(f"      [OK] Distribusi kelas:\n{df[TARGET].value_counts().to_string()}\n")
    return df


# ─────────────────────────────────────────────
# 2. PREPROCESSING
# ─────────────────────────────────────────────
def preprocess(df: pd.DataFrame):
    print("[2/6] Preprocessing...")

    # Drop missing values
    before = len(df)
    df = df.dropna(subset=FEATURES + [TARGET])
    after  = len(df)
    if before != after:
        print(f"      [WARNING] Dropped {before - after} baris dengan nilai kosong")

    X = df[FEATURES].values
    y = df[TARGET].values

    # Label encoding
    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    print(f"      [OK] Kelas yang ditemukan: {list(le.classes_)}")
    print(f"      [OK] Jumlah kelas: {len(le.classes_)}\n")
    return X, y_encoded, le

# ─────────────────────────────────────────────
# 3. SMOTE — HANDLE CLASS IMBALANCE
# ─────────────────────────────────────────────
def apply_smote(X_train, y_train):
    print("[3/6] Menerapkan SMOTE untuk menangani class imbalance...")
    smote = SMOTE(random_state=RANDOM_STATE)
    X_res, y_res = smote.fit_resample(X_train, y_train)
    print(f"      [OK] Sebelum SMOTE: {X_train.shape[0]} sampel")
    print(f"      [OK] Sesudah SMOTE : {X_res.shape[0]} sampel\n")
    return X_res, y_res


# ─────────────────────────────────────────────
# 4. TRAINING + HYPERPARAMETER TUNING
# ─────────────────────────────────────────────
def train(X_train, y_train):
    print("[4/6] Training Random Forest dengan GridSearchCV...")

    param_grid = {
        "n_estimators"     : [100, 200, 300],
        "max_depth"        : [None, 10, 20, 30],
        "min_samples_split": [2, 5, 10],
        "min_samples_leaf" : [1, 2, 4],
    }

    rf  = RandomForestClassifier(random_state=RANDOM_STATE, n_jobs=-1)
    cv  = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

    grid_search = GridSearchCV(
        estimator  = rf,
        param_grid = param_grid,
        cv         = cv,
        scoring    = "f1_weighted",
        n_jobs     = -1,
        verbose    = 1
    )
    grid_search.fit(X_train, y_train)

    print(f"\n      [OK] Best params : {grid_search.best_params_}")
    print(f"      [OK] Best CV score: {grid_search.best_score_:.4f}\n")
    return grid_search.best_estimator_, grid_search.best_params_

# ─────────────────────────────────────────────
# 5. EVALUASI MODEL
# ─────────────────────────────────────────────
def evaluate(model, X_test, y_test, le: LabelEncoder) -> dict:
    print("[5/6] Evaluasi model pada data test...")
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    f1  = f1_score(y_test, y_pred, average="weighted")

    print(f"      [OK] Accuracy : {acc:.4f}")
    print(f"      [OK] F1 Score : {f1:.4f}")
    print(f"\n{classification_report(y_test, y_pred, target_names=le.classes_)}")

    # Feature importance
    importances = dict(zip(FEATURES, model.feature_importances_.tolist()))
    print(f"      [OK] Feature importances: {importances}\n")

    return {
        "accuracy"          : round(acc, 4),
        "f1_score_weighted" : round(f1, 4),
        "feature_importances": importances,
        "classes"           : list(le.classes_)
    }

# ─────────────────────────────────────────────
# 6. SIMPAN MODEL & METADATA
# ─────────────────────────────────────────────
def save_artifacts(model, le: LabelEncoder, best_params: dict, metrics: dict):
    print("[6/6] Menyimpan model dan metadata...")
    os.makedirs(MODEL_DIR, exist_ok=True)

    joblib.dump(model, MODEL_PATH)
    joblib.dump(le,    ENCODER_PATH)
    print(f"      [OK] Model disimpan   : {MODEL_PATH}")
    print(f"      [OK] Encoder disimpan : {ENCODER_PATH}")

    metadata = {
        "trained_at"   : datetime.now().isoformat(),
        "dataset_path" : DATASET_PATH,
        "features"     : FEATURES,
        "target"       : TARGET,
        "best_params"  : best_params,
        "metrics"      : metrics,
        "model_type"   : "RandomForestClassifier",
    }
    with open(METADATA_PATH, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"      [OK] Metadata disimpan: {METADATA_PATH}\n")
    print("=" * 50)
    print("Training selesai!")
    print("=" * 50)


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
def main():
    print("=" * 50)
    print("  AQUACULTURE ML - TRAINING PIPELINE")
    print("=" * 50 + "\n")

    df                       = load_dataset(DATASET_PATH)
    X, y_encoded, le         = preprocess(df)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_encoded, test_size=TEST_SIZE,
        random_state=RANDOM_STATE, stratify=y_encoded
    )
    X_train_res, y_train_res = apply_smote(X_train, y_train)
    best_model, best_params  = train(X_train_res, y_train_res)
    metrics                  = evaluate(best_model, X_test, y_test, le)
    save_artifacts(best_model, le, best_params, metrics)


if __name__ == "__main__":
    main()