# -*- coding: utf-8 -*-
"""evaluate_fish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Ax7SNoO53DTPgigTc9fyjNEPrPpCPjZ
"""

import os
import json
import joblib
import numpy as np
from datetime import datetime, timezone

# KONFIGURASI PATH

MODEL_DIR    = "/content/drive/MyDrive/aquaculture_ml/models"
MODEL_PATH   = os.path.join(MODEL_DIR, "fish_model.pkl")
ENCODER_PATH = os.path.join(MODEL_DIR, "label_encoder.pkl")
OUTPUT_DIR   = "/content/drive/MyDrive/aquaculture_ml/outputs"

FEATURES = ["ph", "temperature", "turbidity"]

# THRESHOLD REKOMENDASI

RECOMMENDATION_THRESHOLD = {
    "recommended"   : 0.65,   # confidence >= 65% → recommended
    "possible"      : 0.35,   # confidence 35–64% → possible
    # di bawah 35%            → not_recommended
}

# Rentang optimal parameter air (referensi umum akuakultur)
PARAMETER_RANGES = {
    "ph": {
        "optimal" : (6.5, 8.5),
        "warning" : (6.0, 9.0),
        # di luar warning → critical
    },
    "temperature": {
        "optimal" : (24.0, 32.0),
        "warning" : (20.0, 35.0),
    },
    "turbidity": {
        "optimal" : (0.0, 25.0),
        "warning" : (0.0, 50.0),
    },
}

# LOAD MODEL (sekali saat startup)
# ─────────────────────────────────────────────
def load_model():
    """
    Load model dan label encoder dari Google Drive.
    Panggil sekali di awal notebook/app.
    """
    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(
            f"Model tidak ditemukan di: {MODEL_PATH}\n"
            "Jalankan train_model.py terlebih dahulu."
        )
    model = joblib.load(MODEL_PATH)
    le    = joblib.load(ENCODER_PATH)
    print(f"✓ Model loaded — {len(le.classes_)} kelas ikan: {list(le.classes_)}\n")
    return model, le

# HELPER: ANALISIS PARAMETER AIR

def _analyze_parameter(param: str, value: float) -> dict:
    """Evaluasi status tiap parameter air (optimal / warning / critical)."""
    ranges  = PARAMETER_RANGES.get(param, {})
    optimal = ranges.get("optimal", (None, None))
    warning = ranges.get("warning", (None, None))

    if optimal[0] is not None and optimal[0] <= value <= optimal[1]:
        status  = "optimal"
        message = f"{param} dalam rentang optimal"
    elif warning[0] is not None and warning[0] <= value <= warning[1]:
        status  = "warning"
        message = f"{param} di luar rentang optimal, perlu perhatian"
    else:
        status  = "critical"
        message = f"{param} di luar batas aman"

    return {
        "value"          : round(value, 2),
        "status"         : status,
        "message"        : message,
        "optimal_range"  : {"min": optimal[0], "max": optimal[1]},
    }


def _get_recommendation_label(confidence: float) -> str:
    """Konversi confidence score ke label rekomendasi."""
    if confidence >= RECOMMENDATION_THRESHOLD["recommended"]:
        return "recommended"
    elif confidence >= RECOMMENDATION_THRESHOLD["possible"]:
        return "possible"
    else:
        return "not_recommended"


def _get_confidence_label(confidence: float) -> str:
    """Label deskriptif untuk confidence score."""
    if confidence >= 0.80:
        return "Very High"
    elif confidence >= 0.65:
        return "High"
    elif confidence >= 0.45:
        return "Medium"
    elif confidence >= 0.25:
        return "Low"
    else:
        return "Very Low"


def _overall_water_status(parameter_analysis: dict) -> str:
    """Status keseluruhan kualitas air berdasarkan analisis tiap parameter."""
    statuses = [v["status"] for v in parameter_analysis.values()]
    if "critical" in statuses:
        return "critical"
    elif "warning" in statuses:
        return "warning"
    else:
        return "good"

# FUNGSI UTAMA: EVALUATE FISH

def evaluate_fish(
    model,
    le,
    fish_name     : str,
    water_condition: dict,
    station_info  : dict = None
) -> dict:

    timestamp = datetime.now(timezone.utc).isoformat()

    # ── Validasi input ──────────────────────────────
    fish_name_clean = fish_name.strip()
    available_fish  = list(le.classes_)

    if fish_name_clean not in available_fish:
        return _error_response(
            timestamp    = timestamp,
            fish_name    = fish_name_clean,
            station_info = station_info,
            error_code   = "FISH_NOT_FOUND",
            message      = (
                f"Ikan '{fish_name_clean}' tidak ada dalam database model. "
                f"Ikan yang tersedia: {available_fish}"
            )
        )

    missing_params = [f for f in FEATURES if f not in water_condition]
    if missing_params:
        return _error_response(
            timestamp    = timestamp,
            fish_name    = fish_name_clean,
            station_info = station_info,
            error_code   = "MISSING_PARAMETERS",
            message      = f"Parameter air tidak lengkap: {missing_params}"
        )

    # ── Prediksi ────────────────────────────────────
    X = np.array([[
        water_condition["ph"],
        water_condition["temperature"],
        water_condition["turbidity"]
    ]])

    proba_array = model.predict_proba(X)[0]                      # probabilitas semua kelas
    fish_index  = list(le.classes_).index(fish_name_clean)
    confidence  = float(proba_array[fish_index])

    # Probability distribution semua ikan (diurutkan descending)
    prob_dist = {
        cls: round(float(prob), 4)
        for cls, prob in sorted(
            zip(le.classes_, proba_array),
            key=lambda x: x[1],
            reverse=True
        )
    }

    # Top 3 rekomendasi alternatif (ikan lain yang paling cocok)
    top3_alternatives = [
        {"fish": cls, "confidence": prob}
        for cls, prob in list(prob_dist.items())[:3]
        if cls != fish_name_clean
    ][:3]

    # ── Analisis parameter air ───────────────────────
    parameter_analysis = {
        feat: _analyze_parameter(feat, water_condition[feat])
        for feat in FEATURES
    }

    # ── Label & status ───────────────────────────────
    recommendation    = _get_recommendation_label(confidence)
    confidence_label  = _get_confidence_label(confidence)
    water_status      = _overall_water_status(parameter_analysis)

    # ── Susun response ───────────────────────────────
    station_block = {}
    if station_info:
        station_block = {
            "station_id" : station_info.get("station_id", "unknown"),
            "name"       : station_info.get("name", ""),
            "description": station_info.get("description", ""),
        }
    else:
        station_block = {"station_id": "unknown", "name": "", "description": ""}

    response = {
        "status"   : "success",
        "timestamp": timestamp,
        "station"  : {
            **station_block,
            "water_condition"   : {f: round(water_condition[f], 2) for f in FEATURES},
            "water_quality_status": water_status,
            "parameter_analysis": parameter_analysis,
        },
        "evaluation": {
            "fish_queried"           : fish_name_clean,
            "recommendation"         : recommendation,          # "recommended" | "possible" | "not_recommended"
            "confidence_score"       : round(confidence, 4),
            "confidence_label"       : confidence_label,        # "Very High" | "High" | "Medium" | "Low" | "Very Low"
            "probability_distribution": prob_dist,
            "top_alternatives"       : top3_alternatives,
        }
    }

    return response

# ERROR RESPONSE FORMAT

def _error_response(timestamp, fish_name, station_info, error_code, message) -> dict:
    return {
        "status"    : "error",
        "timestamp" : timestamp,
        "error_code": error_code,
        "message"   : message,
        "fish_queried": fish_name,
        "station_id": station_info.get("station_id", "unknown") if station_info else "unknown",
    }


# SIMPAN HASIL KE FILE (opsional, untuk logging)

def save_result(result: dict, filename: str = None):
    """Simpan hasil evaluasi ke outputs/ sebagai JSON."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    if filename is None:
        ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"evaluation_{ts}.json"

    output_path = os.path.join(OUTPUT_DIR, filename)
    with open(output_path, "w") as f:
        json.dump(result, f, indent=2)
    print(f"✓ Hasil disimpan: {output_path}")
    return output_path

# DEMO (jalankan langsung untuk test)

if __name__ == "__main__":
    from simulate_iot import init_iot_simulator, get_station_by_id

    print("=" * 50)
    print("  AQUACULTURE ML — FISH EVALUATOR")
    print("=" * 50 + "\n")

    # Load model
    model, le = load_model()

    # Simulasi: user pilih pond_1 dan drag & drop ikan "Tilapia"
    pond_df      = init_iot_simulator()
    station_info = get_station_by_id(pond_df, "pond_1")

    result = evaluate_fish(
        model           = model,
        le              = le,
        fish_name       = "Tilapia",
        water_condition = station_info["water_condition"],
        station_info    = station_info
    )

    print(json.dumps(result, indent=2))
    save_result(result, "evaluation_result.json")